// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dizmswygqlosnjwwjtfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpem1zd3lncWxvc25qd3dqdGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2OTAzMjIsImV4cCI6MjA2NzI2NjMyMn0.PTOAvv5_OG4p6ofslXhkrx7rAy7s4lXFoyDuhdr4d3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});